class VarGlobal {
  static List list_jadwal_rapat = [];
  static String pesanSnackBar = "";

  //DATA USER LOGIN
  static String nama = '';
  static String id_user = '';
  static String token = '';
  static String nip = '';
  static String nama_jabatan = '';

  //
  static String masa_kerja = '';
  static String unit_kerja = '';
  static String atasan = '';
  static String pejabat = '';
  static String mengetahui = '';

  static List<String> atasan_langsung = [
    'Prof. Dr. Hasbi, M.H. (Sekretaris Mahkamah Agung RI)',
    'Dr. H. Hari Sugiharto, S.H. M.H. (Direktur Pembinaan Tenaga Teknis Dan Administrasi Peradilan Tata Usaha Negara)',
    'Drs. H. Ach. Jufri, S.H., M.H. (Sekretaris Direktorat Jenderal Badan Peradilan Militer dan Peradilan Tata Usaha Negara)',
    'Marsekal Pertama TNI Edi Wuryanto, S.IP., C.Fr.A (Direktur Pembinaan Tenaga Teknis dan Administrasi Peradilan Militer)',
    'I Gusti Ngurah Putra Mahendra, S.H., M.H. (Kabag Umum Sekretariat)',
    'Yuda Aji Wibawa, S.H., M.H. (Kasubdit Pembinaan Tenaga Teknis Ditbinganismintun)',
    'Sudiyono, S.H. MH. (Kasubdit Pembinaan Administrasi Ditbinganismintun)',
    'Kolonel Chk Muhaemin, S.H., M.H. (Kasubdit Pengembangan Tenaga Teknis Ditbinganisminmil)',
    'Dwi Maria Puspitasari, S.Kom., M.M. (Kasubbag Mutasi Sekretariat)',
    'Dandy Capryanto Hermawan, S.H.,M.H. (Kasi Bimbingan dan Monitoring Ditbinganisminmil)',
    'Venny Adelina Tumuyu, S.H., M.Si. (Kasi Peningkatan Mutu Panitera Ditbinganiminmil)',
    'Teguh Ahmadi, S.E., M.M. (Kabag Perencanaan dan Keuangan Sekretariat)',
    'Erna Rosmawati, S.H. (Kasubbag Tata Usaha Ditbinganismintun)',
    'Catur Adi Wasono, S.E., M.M. (Kasubbag Rumah Tangga Sekretariat)',
    'Dwianto Budiman, S.Kom., M.M. (Kasi Bimbingan dan Monitoring Ditbinganismintun)',
    'Ira Farella Anggraini, S.E., M.M. (Kasubbag Perencanaan Program dan Penyusunan Anggaran Sekretariat)',
    'Jefri Ardianto, S.T., M.M. (Kabag Organisasi dan Tata Laksana Sekretariat)',
    'Arianie Amanda, S.E. (Kasi Statistik dan Dokumentasi Ditbinganisminmil)',
    'Lidya Dayana Saktinegara, S.H., S.E., M.M. (Kasi Peningkatan Mutu Panitera dan Jurusita Ditbinganismintun)',
    'Hartati Wuryaningdyah, S.E., M.M. (Kabag Kepegawaian Sekretariat)',
    'Lamtur Pandapotan Simanullang, S.E., M.M. (Kasi Peningkatan Mutu Hakim Ditbinganisminmil)',
    'Happy Rahmawati, S.E., M.M. (Kasi Tata Kelola Ditbinganisminmil)',
    'Metty Indrasari, S.H. (Kasi Mutasi Panitera dan Jurusita Ditbinganismintun)',
    'Budi Hadi, A.Md. (Kasubbag Perlengkapan Sekretariat)',
    'Meylan, S.Sos.,M.M. (Kasi Tata Kelola Ditbinganismintun)',
    'Welly Walbarkah, S.Kom (Kasubbag Dokumentasi dan Informasi Sekretariat)',
    'Intan Sari Widya Ningrum, S.H.,M.H. (Kasi Statistik dan Dokumentasi Ditbinganismintun)',
    'Suryaningsih, S.Kom. (Kasi Peningkatan Mutu Hakim Ditbinganismintun)',
    'Wanda, S.H. (Kasi Mutasi Hakim Ditbinganismintun)',
    'Tina Rizkiati, S.E., M.M. (Kasubbag Ketatalaksanaan Sekretariat)',
    'Hari Arief Darmawan, S.H., M.H. (Kasubbag Anggaran dan Perbendaharaan Sekretariat)',
    'Mayor CHK Heriyanto, S.H. (Kasi Mutasi Panitera dan Jurusita Ditbinganisminmil)',
    'Yudo Ari Kasdaroyo (Pengadministrasi Data Penyajian dan Publikasi)',
    'Wahyudin, S.H. (Kasubbag Tata Usaha Sekretariat)',
    'Hasanudin, S.H. (Kasubbag Pemberhentian dan Pensiun Sekretariat)',
    'Resa Januar Pratama, S.T. (Kasubbag Umum Kepegawaian Sekretariat)',
    'Wiwit Andi Hartanti, A.Md. (Kasi Evaluasi dan Rasionalisasi Ditbinganisminmil)',
    'Ajie Putra Mula Kusuma, S.H.,M.H. (Kasubbag Tata Usaha Ditbinganisminmil)',
    'Hilda Riandini, S.Kom. (Analis Pelaksanaan Anggaran Ditjen Badilmiltun)',
    'Sofiyatul Mu`Minah, S.Kom. (Analis Rencana Program dan Kegiatan)',
    'Serka Arip Junaidi, S.H. (Pengelola Data Ditjen Badilmiltun)',
    'Sertu Anom Satria Yudhistira (Pengadministrasi Persuratan Ditjen Badilmiltun)',
    'Kopka Hendra Gian Sudaryanto (Pengadministrasi Umum Ditjen Badilmiltun)',
    'Koptu Eko Budi Santoso (Ajudan Ditjen Badilmiltun)',
    'Serma Yudha Ade Saputra, S.H., M.H. (Pengelola Data Ditjen Badilmiltun)',
    'Praka Surono (Pengadministrasi Umum Ditjen Badilmiltun)',
    'Theo Afianto, S.T. (Pranata Komputer Ahli Pertama)',
    'Choyrul Mala, S.Hum. (Arsiparis Ahli Pertama)',
    ' Victor Albadiu Ratib, S.H. (Kasubbag Akuntansi Sekretariat)',
    'Meitina Kardina, S.E. (Kasi Evaluasi dan Rasionalisasi Ditbinganismintun)',
    'Ardi Bagas Pratama, A.Md. (PPNPN)',
    'Aziz Lathif Yusuf (PPNPN)',
    'Henry Sembung (PPNPN)',
    'Indah Putri Retno Astrini, S.Ikom (PPNPN)',
    'Jenifer Aurora Michelle, S.H. (PPNPN)',
    'Kurniawan (PPNPN)',
    'Muhammad Heru (PPNPN)',
    'Nadia Sifa Auliya, S.Kom. (PPNPN)',
    'Priandi (PPNPN)',
    'Robbi Atil Adawiyah, S.E. (PPNPN)',
    'Santi Resmila Hutauruk, S.H. (PPNPN)',
    'Sherly Valentina Isabela (PPNPN)',
    'Sukirman (PPNPN)',
    'Vinda Pratiwi, S.H. (PPNPN)',
    'Wahyuningsih, S.H. (PPNPN)',
    'Agus Abdur Rahman, S.H., M.H. (Hakim Yustisial)',
    'Retno Ariyani, S.H., M.H. (Hakim Yustisial)',
    'Dheo Agustian S., S.H. (Pengadministrasi Persuratan Ditjen Badilmiltun)',
    'Mayor Chk K.G Raegen, SH (Hakim Yustisial)',
    'Rahmawati Sukma Wardani, A.Md.Kb.N. (Pranata Keuangan APBN Pelaksana/Terampil)',
    'Febriana Avioriska, S.H. (Analis Perkara Peradilan)',
    'Febry Indra Gunawan Sitorus, S.H. (Analis Perkara Peradilan)',
    'Muhammad Bagus Tri Prasetyo, S.H. (Analis Perkara Peradilan)',
    'Dona Pratama Jonaidi, S.H. (Analis Perkara Peradilan)',
    'Ilham Putra Dewanta, S.H. (Analis Perkara Peradilan)',
    'Anton Nursaleh Siregar, S.H. (Analis Perkara Peradilan)',
    'Safira Salsabila, S.H. (Analis Perkara Peradilan)',
    'Siti Purwanti, S.H. (Analis Perkara Peradilan)',
    'Tarsicius Batistuta Telaumbanua, S.H. (Analis Perkara Peradilan)',
    'Indra Yani Gustami Prayitno, S.H (Analis Perkara Peradilan)',
    'Kolonel Chk. Widodo, S.H. (Kasubdit Pembinaan Tenaga Teknis Ditbinganisminmil)',
    'Jumanto (PPNPN)',
    'Sertu (K) Estarina Aritonang (Pengadministrasi Persuratan Ditjen Badilmiltun)',
    'Bayu Febriansyah, S.Sos (PPNPN)',
    'Kapten Dede Juhaedi, S.Pd., S.H., M.H. (BP pada Ditbinganismin MIL)',
    'Serka Agus Sudarsono (Ajudan Ditjen Badilmiltun)',
    'Letkol Kum Irwan Tasri, S.H., M.H., M.Han. (Kasi Mutasi Hakim Ditbinganisminmil)',
    'Dr. Nasrifal, S.H., M.H. (Kasubdit Pengembangan Tenaga Teknis Ditbinganismintun)',
    'Hendro Wuriyanto, S.E. (PPNPN)',
    'Vina Rahmajulia, S.E. (PPNPN)',
    'Kolonel Laut (H) Dr. Marimin, S.H., M.M., M.H. (Kasubdit Pembinaan Administrasi Ditbinganisminmil)',
    'Mifta Widyastuti, A.Md.M. (Diperbantukan sebagai Pengolah Data Informasi dan Hukum Sekretariat)',
    'Lettu Chk (K) Raeny Dewi Puspita, S.H. (BP Pengadministrasi Persuratan pada Ditbinganismin Mil)',
    'Nanang Nurwahyudi, S.H. (Analis Perkara Peradilan)',
    'Kurnia Ningtyas, A.Md. (Arsiparis Pelaksana)',
    'H. Bambang Myanto, S.H., M.H. (Plt. Direktur Jenderal Badan Peradilan Militer dan Peradilan Tata Usaha Negara',
    'Rionaldo Sahat Sigalingging, S.Kom. (Kasubbag Kelembagaan dan Pelaporan Sekretariat)',
  ];
  static List<String> pejabat_berwewenang = [
    'Prof. Dr. Hasbi, M.H. (Sekretaris Mahkamah Agung RI)',
    'Dr. H. Hari Sugiharto, S.H. M.H. (Direktur Pembinaan Tenaga Teknis Dan Administrasi Peradilan Tata Usaha Negara)',
    'Drs. H. Ach. Jufri, S.H., M.H. (Sekretaris Direktorat Jenderal Badan Peradilan Militer dan Peradilan Tata Usaha Negara)',
    'Marsekal Pertama TNI Edi Wuryanto, S.IP., C.Fr.A (Direktur Pembinaan Tenaga Teknis dan Administrasi Peradilan Militer)',
    'I Gusti Ngurah Putra Mahendra, S.H., M.H. (Kabag Umum Sekretariat)',
    'Yuda Aji Wibawa, S.H., M.H. (Kasubdit Pembinaan Tenaga Teknis Ditbinganismintun)',
    'Sudiyono, S.H. MH. (Kasubdit Pembinaan Administrasi Ditbinganismintun)',
    'Kolonel Chk Muhaemin, S.H., M.H. (Kasubdit Pengembangan Tenaga Teknis Ditbinganisminmil)',
    'Dwi Maria Puspitasari, S.Kom., M.M. (Kasubbag Mutasi Sekretariat)',
    'Dandy Capryanto Hermawan, S.H.,M.H. (Kasi Bimbingan dan Monitoring Ditbinganisminmil)',
    'Venny Adelina Tumuyu, S.H., M.Si. (Kasi Peningkatan Mutu Panitera Ditbinganiminmil)',
    'Teguh Ahmadi, S.E., M.M. (Kabag Perencanaan dan Keuangan Sekretariat)',
    'Erna Rosmawati, S.H. (Kasubbag Tata Usaha Ditbinganismintun)',
    'Catur Adi Wasono, S.E., M.M. (Kasubbag Rumah Tangga Sekretariat)',
    'Dwianto Budiman, S.Kom., M.M. (Kasi Bimbingan dan Monitoring Ditbinganismintun)',
    'Ira Farella Anggraini, S.E., M.M. (Kasubbag Perencanaan Program dan Penyusunan Anggaran Sekretariat)',
    'Jefri Ardianto, S.T., M.M. (Kabag Organisasi dan Tata Laksana Sekretariat)',
    'Arianie Amanda, S.E. (Kasi Statistik dan Dokumentasi Ditbinganisminmil)',
    'Lidya Dayana Saktinegara, S.H., S.E., M.M. (Kasi Peningkatan Mutu Panitera dan Jurusita Ditbinganismintun)',
    'Hartati Wuryaningdyah, S.E., M.M. (Kabag Kepegawaian Sekretariat)',
    'Lamtur Pandapotan Simanullang, S.E., M.M. (Kasi Peningkatan Mutu Hakim Ditbinganisminmil)',
    'Happy Rahmawati, S.E., M.M. (Kasi Tata Kelola Ditbinganisminmil)',
    'Metty Indrasari, S.H. (Kasi Mutasi Panitera dan Jurusita Ditbinganismintun)',
    'Budi Hadi, A.Md. (Kasubbag Perlengkapan Sekretariat)',
    'Meylan, S.Sos.,M.M. (Kasi Tata Kelola Ditbinganismintun)',
    'Welly Walbarkah, S.Kom (Kasubbag Dokumentasi dan Informasi Sekretariat)',
    'Intan Sari Widya Ningrum, S.H.,M.H. (Kasi Statistik dan Dokumentasi Ditbinganismintun)',
    'Suryaningsih, S.Kom. (Kasi Peningkatan Mutu Hakim Ditbinganismintun)',
    'Wanda, S.H. (Kasi Mutasi Hakim Ditbinganismintun)',
    'Tina Rizkiati, S.E., M.M. (Kasubbag Ketatalaksanaan Sekretariat)',
    'Hari Arief Darmawan, S.H., M.H. (Kasubbag Anggaran dan Perbendaharaan Sekretariat)',
    'Mayor CHK Heriyanto, S.H. (Kasi Mutasi Panitera dan Jurusita Ditbinganisminmil)',
    'Yudo Ari Kasdaroyo (Pengadministrasi Data Penyajian dan Publikasi)',
    'Wahyudin, S.H. (Kasubbag Tata Usaha Sekretariat)',
    'Hasanudin, S.H. (Kasubbag Pemberhentian dan Pensiun Sekretariat)',
    'Resa Januar Pratama, S.T. (Kasubbag Umum Kepegawaian Sekretariat)',
    'Wiwit Andi Hartanti, A.Md. (Kasi Evaluasi dan Rasionalisasi Ditbinganisminmil)',
    'Ajie Putra Mula Kusuma, S.H.,M.H. (Kasubbag Tata Usaha Ditbinganisminmil)',
    'Hilda Riandini, S.Kom. (Analis Pelaksanaan Anggaran Ditjen Badilmiltun)',
    'Sofiyatul Mu`Minah, S.Kom. (Analis Rencana Program dan Kegiatan)',
    'Serka Arip Junaidi, S.H. (Pengelola Data Ditjen Badilmiltun)',
    'Sertu Anom Satria Yudhistira (Pengadministrasi Persuratan Ditjen Badilmiltun)',
    'Kopka Hendra Gian Sudaryanto (Pengadministrasi Umum Ditjen Badilmiltun)',
    'Koptu Eko Budi Santoso (Ajudan Ditjen Badilmiltun)',
    'Serma Yudha Ade Saputra, S.H., M.H. (Pengelola Data Ditjen Badilmiltun)',
    'Praka Surono (Pengadministrasi Umum Ditjen Badilmiltun)',
    'Theo Afianto, S.T. (Pranata Komputer Ahli Pertama)',
    'Choyrul Mala, S.Hum. (Arsiparis Ahli Pertama)',
    ' Victor Albadiu Ratib, S.H. (Kasubbag Akuntansi Sekretariat)',
    'Meitina Kardina, S.E. (Kasi Evaluasi dan Rasionalisasi Ditbinganismintun)',
    'Ardi Bagas Pratama, A.Md. (PPNPN)',
    'Aziz Lathif Yusuf (PPNPN)',
    'Henry Sembung (PPNPN)',
    'Indah Putri Retno Astrini, S.Ikom (PPNPN)',
    'Jenifer Aurora Michelle, S.H. (PPNPN)',
    'Kurniawan (PPNPN)',
    'Muhammad Heru (PPNPN)',
    'Nadia Sifa Auliya, S.Kom. (PPNPN)',
    'Priandi (PPNPN)',
    'Robbi Atil Adawiyah, S.E. (PPNPN)',
    'Santi Resmila Hutauruk, S.H. (PPNPN)',
    'Sherly Valentina Isabela (PPNPN)',
    'Sukirman (PPNPN)',
    'Vinda Pratiwi, S.H. (PPNPN)',
    'Wahyuningsih, S.H. (PPNPN)',
    'Agus Abdur Rahman, S.H., M.H. (Hakim Yustisial)',
    'Retno Ariyani, S.H., M.H. (Hakim Yustisial)',
    'Dheo Agustian S., S.H. (Pengadministrasi Persuratan Ditjen Badilmiltun)',
    'Mayor Chk K.G Raegen, SH (Hakim Yustisial)',
    'Rahmawati Sukma Wardani, A.Md.Kb.N. (Pranata Keuangan APBN Pelaksana/Terampil)',
    'Febriana Avioriska, S.H. (Analis Perkara Peradilan)',
    'Febry Indra Gunawan Sitorus, S.H. (Analis Perkara Peradilan)',
    'Muhammad Bagus Tri Prasetyo, S.H. (Analis Perkara Peradilan)',
    'Dona Pratama Jonaidi, S.H. (Analis Perkara Peradilan)',
    'Ilham Putra Dewanta, S.H. (Analis Perkara Peradilan)',
    'Anton Nursaleh Siregar, S.H. (Analis Perkara Peradilan)',
    'Safira Salsabila, S.H. (Analis Perkara Peradilan)',
    'Siti Purwanti, S.H. (Analis Perkara Peradilan)',
    'Tarsicius Batistuta Telaumbanua, S.H. (Analis Perkara Peradilan)',
    'Indra Yani Gustami Prayitno, S.H (Analis Perkara Peradilan)',
    'Kolonel Chk. Widodo, S.H. (Kasubdit Pembinaan Tenaga Teknis Ditbinganisminmil)',
    'Jumanto (PPNPN)',
    'Sertu (K) Estarina Aritonang (Pengadministrasi Persuratan Ditjen Badilmiltun)',
    'Bayu Febriansyah, S.Sos (PPNPN)',
    'Kapten Dede Juhaedi, S.Pd., S.H., M.H. (BP pada Ditbinganismin MIL)',
    'Serka Agus Sudarsono (Ajudan Ditjen Badilmiltun)',
    'Letkol Kum Irwan Tasri, S.H., M.H., M.Han. (Kasi Mutasi Hakim Ditbinganisminmil)',
    'Dr. Nasrifal, S.H., M.H. (Kasubdit Pengembangan Tenaga Teknis Ditbinganismintun)',
    'Hendro Wuriyanto, S.E. (PPNPN)',
    'Vina Rahmajulia, S.E. (PPNPN)',
    'Kolonel Laut (H) Dr. Marimin, S.H., M.M., M.H. (Kasubdit Pembinaan Administrasi Ditbinganisminmil)',
    'Mifta Widyastuti, A.Md.M. (Diperbantukan sebagai Pengolah Data Informasi dan Hukum Sekretariat)',
    'Lettu Chk (K) Raeny Dewi Puspita, S.H. (BP Pengadministrasi Persuratan pada Ditbinganismin Mil)',
    'Nanang Nurwahyudi, S.H. (Analis Perkara Peradilan)',
    'Kurnia Ningtyas, A.Md. (Arsiparis Pelaksana)',
    'H. Bambang Myanto, S.H., M.H. (Plt. Direktur Jenderal Badan Peradilan Militer dan Peradilan Tata Usaha Negara',
    'Rionaldo Sahat Sigalingging, S.Kom. (Kasubbag Kelembagaan dan Pelaporan Sekretariat)',
  ];
}
